// Generated by https://quicktype.io

export interface DashboardResponse {
    numberOrders:   number;
    paidOrders:     number;
    numberClients:  number;
    numberProducts: number;
    noInventory:    number;
    lowInventory:   number;
    noPaidOrders:   number;
}
